version: 2
jobs:
  build:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: cimg/python:3.10.1  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
stpes:
  -checkout
  -run: lscpu